### ISSUE TITLE
Implement traits of external crates

### ISSUE THREAD

**Issue by daxpedda** [ModProg/derive-where#10]
We discussed implementing this for `Zeroize` for example, this might not be necessary if `Zeroize` can be fixed with a PR.
We should explore this further.

**Comment by ModProg** [comment]
While 3rd party crates can be fixed via a PR, this adds a new syntax for each crate, so being able to do it with a `standard` way might be interesting in itself, the only issue is that that adds more traits to maintain which could be unstable.

**Comment by daxpedda** [comment]
We probably will need to implement something like this too then:
- `#[derive_where(Zeroize(drop)]` à la `#[zeroize(drop)]`
- `#[derive_where(Zeroize(crate = "zeroize_")]` à la [`#[serde(crate = "..."]`](https://serde.rs/container-attrs.html#crate)
