### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by daxpedda** [ModProg/derive-where#2]
Currently the input on `#[derive_where(xxx)]` is not validated properly and sometimes doesn't output useful error messages.

Thinks we want to cover:
- [x] Syntax:
  - [x] Support not inputting any generics
  - [x] Check for duplicate commas
  - [x] Check for duplicate semicolons
  - [x] Pseudo-validate that generics are actual generics
  - [x] Support multiple traits to implement
- [x] Applicability
  - [x] Don't support items without generics, error message should say to use standard derives instead
  - [x] Better error message on unions, currently it's panicking
- [x] Evaluate if `proc_macro_error` can be replaced with something hand-written

**Comment by daxpedda** [comment]
Research https://docs.rs/proc-macro-error/1.0.4/proc_macro_error/.

**Comment by ModProg** [comment]
Well probably just use empty bounds, we could use look_ahead and try parse the DeriveWhere and if it fails parse only Trait list.
so #[derive_where(Clone)] without ; and T.

**Comment by daxpedda** [comment]
We could also test for parsing `;`, if we don't find a `;`, we can assume it's only traits. We do support no generics, but traits are mandatory.
