### ISSUE TITLE
Auto-deref

### ISSUE THREAD

**Issue by daxpedda** [ModProg/derive-where#20]
I found the following issue, which affects `Zeroize` quiet heavily:
```rust
struct SliceDeref([u8; 1]);

impl Deref for SliceDeref {
    type Target = [u8];

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl DerefMut for SliceDeref {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

#[derive_where(Zeroize; T)]
struct Test3<T>(T, SliceDeref);

let mut test = Test3(42, SliceDeref([42]));
test.zeroize();

assert_eq!(test.0, 0);
assert_eq!(test.1 .0, [0]);
```

This will fail because `SliceDeref` doesn't implement `Zeroize` and we call `zeroize` by using the fully-qualified syntax, which prevents auto-deref.

Obviously this affects all traits, as far as I know there is no way to use FQS and auto-deref. So my current thought is to introduce another attribute that basically forces derive-where to use auto-deref instead of FQS, something like `#[derive_where(auto_deref(Clone, Zeroize))]`?

**Comment by ModProg** [comment]
Does this work with standard derive?

I would prefer something like maybe `#[derive_where_deref(Zeroize; T)`.

**Comment by daxpedda** [comment]
> Does this work with standard derive?

It doesn't as far as I know.
> I would prefer something like maybe `#[derive_where_deref(Zeroize; T)`.

That's much better actually.

**Comment by daxpedda** [comment]
I just tried the following:
```rust
use core::ops::Deref;

struct SliceDeref([u8; 1]);

impl Deref for SliceDeref {
    type Target = [u8];

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

#[derive(Clone)]
struct Test(SliceDeref);
```
This definitely doesn't work, so I guess this would be another feature that we will have over standard derive, lol.

**Comment by ModProg** [comment]
ok, one thing that might be actually a reason for using more your syntax would be:

```rs
struct HasDeref;
struct NeedsFGS; 

#[derive_where(Zeroize;with_deref(A),B)
struct HasBoth(A,B);
```

**Comment by ModProg** [comment]
Does using deref work for all Traits, tho, or do we need to have some kind of check there. 
Because Clone needs to return the actual thing and not the clone of the deref.

**Comment by daxpedda** [comment]
> ok, one thing that might be actually a reason for using more your syntax would be:
> 
> ```rust
> struct HasDeref;
> struct NeedsFQS; 
> 
> #[derive_where(Zeroize; deref(A), B)]
> struct HasBoth(A,B);
> 
> 
> let mut test = HasBoth(HasDeref, NeedsFQS);
> test.zeroize();
> ```

This won't be necessary, because the only reason you need FQS is to avoid collision, if you can use auto-deref, you might as well use them on everything.

> Does using deref work for all Traits, tho, or do we need to have some kind of check there. Because Clone needs to return the actual thing and not the clone of the deref.

You are right, I did some testing, and apparently most standard traits don't support auto-deref anyway. As far as my testing goes only `Hash` supports this.

I propose the following:
- Use auto-deref for `Zeroize` by default, this is what `Zeroize`s derive does too
- Add an FQS option for `Zeroize`
- Optionally add an auto-deref option to `Hash`? (I'm in favor of skipping that)

**Comment by ModProg** [comment]
> You are right, I did some testing, and apparently most standard traits don't support auto-deref anyway. As far as my testing goes only Hash supports this.

Shouldn't debug and the comparisons also work?

> This won't be necessary, because the only reason you need FQS is to avoid collision, if you can use auto-deref, you might as well use them on everything.

But if you have one generic argument that needs FQS to avoid collision? Like if NeedsFQS has a zeroize function that is not the correct one :thinking: or am I mixing something up here?

**Comment by daxpedda** [comment]
> Shouldn't debug and the comparisons also work?

Auto-deref only works if it's a method on what you want to dereference. `Debug` is a method on `DebugStruct` or `DebugTuple`. `PartialEq` uses the `eq` method, but it takes another of the same type as a parameter, so the `self` can be auto-deref, but not the parameter.
> But if you have one generic argument that needs FQS to avoid collision? Like if NeedsFQS has a zeroize function that is not the correct one 🤔 or am I mixing something up here?

No, you are absolutely right, I was only thinking of the use-case of having trait collisions, but the method could be colliding as well.

I'm honestly fine with drawing the line here. I feel like we are over-engineering it here with no real use-case in mind, nobody names their methods `zeroize` and then plans to use the zeroize crate on top of it, I hope at least, lol. Which isn't the case with `Hash` I must say though, happened to myself that I wanted to implement `hash` on a type that has a method with the same name.

The issue that we really need to address though is auto-deref for zeroize, because that's a use-case I'm bumping myself into. `GenericArray` for example, is a widely used type/crate in the cryptographic ecosystem, it doesn't implement `Zeroize`, which is no problem because of auto-deref usually.

I'm still returning to switching `Zeroize` to auto-deref and provide an option for FQS.

**Comment by ModProg** [comment]
I think if the standard derive for Zeroize does it this is totally fine, I think as a general rule, If there is not a real actual use case we can support on top of the standards, we should not implement useless features there. So I think this is the way to go. 

We might add an option to have autoderef for Hash, but I don't know if there really is a reason for that, as most things that can deref to something don't probably have no derive Hash themselves.
