### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by ModProg** [ModProg/derive-where#3]
- [ ] Integration tests
  - [ ] Tuple
    - [x] One field
    - [ ] Two fields
    - [x] Three fields
  - [ ] Struct
    - [x] One field
    - [ ] Two fields
    - [x] Three fields
  - [ ] Enum
    - [ ] One variant
      - [x] Tuple with one field
      - [x] Struct with one field
      - [ ] Tuple with two fields
      - [ ] Struct with two fields
      - [x] Tuple with three fields
      - [x] Struct with three fields
    - [ ] Two variants
      - [ ] Both variants structs
        - [ ] First struct with no fields
        - [ ] Second struct with no fields
        - [ ] Both structs with one field
        - [ ] Both structs with two fields
        - [ ] Both structs with three fields
      - [ ] Both variants tuples
        - [ ] First tuple with no fields
        - [ ] Second tuple with no fields
        - [ ] Both tuple with one field
        - [ ] Both tuple with two fields
        - [ ] Both tuple with three fields
      - [ ] First variant struct, second variant unit
        - [ ] Struct with one field
        - [ ] Struct with two fields
        - [ ] Struct with three fields
      - [ ] First variant unit, second variant struct
        - [ ] Struct with one field
        - [ ] Struct with two fields
        - [ ] Struct with three fields
      - [ ] First variant tuple, second variant unit
        - [ ] Tuple with one field
        - [ ] Tuple with two fields
        - [ ] Tuple with three fields
      - [ ] First variant unit, second variant tuple
        - [ ] Tuple with one field
        - [ ] Tuple with two fields
        - [ ] Tuple with three fields
    - [ ] Three variants
      - [ ] All variants structs
        - [ ] First variant struct with no fields
        - [ ] Second variant struct with no fields
        - [ ] Third variant struct with no fields
        - [ ] First and second variants structs with no fields
        - [ ] First and third variants structs with no fields
        - [ ] Second and third variants structs with no fields
      - [ ] First variant unit
        - [ ] All others structs
        - [ ] All others tuples
        - [ ] Second variant struct, third variant tuple
        - [ ] Second variant tuple, third variant struct
      - [ ] Second variant unit
        - [ ] All others structs
        - [ ] All others tuples
        - [ ] First variant struct, third variant tuple
        - [ ] First variant tuple, third variant struct
      - [ ] Third variant unit
        - [ ] All others structs
        - [ ] All others tuples
        - [x] First variant struct, second variant tuple
        - [ ] First variant tuple, second variant struct
      - [ ] First and second variant unit
        - [ ] Third variant struct
        - [ ] Third variant tuple
      - [ ] First and third variant unit
        - [ ] Second variant struct
        - [ ] Second variant tuple
      - [ ] Second and third variant unit
        - [ ] First variant struct
        - [ ] First variant tuple
  - [x] Edge-cases
    - [x] Associated type generics: `<T as Trait>::Type>; Clone`
    - [x] Empty bound: `Clone, Debug`
    - [x] Custom bound: `T: SomeTraitRequiringClone; Clone`
    - [x] Where clause:
      ``` rust
      struct Test<T>
      where T: SomeTrait
      {
        ...
      }
      ```
- [x] Derive tests
  - [x] Struct
  - [x] Tuple
  - [x] Enum
    - [x] Struct
    - [x] Tuple
    - [x] Unit
  - [x] Edge-cases
    - [x] No generic type parameters
    - [x] Associated type generics: `<T as Trait>::Type; Clone`
    - [x] Custom bound: `T: SomeTraitRequiringClone; Clone`
    - [x] Where clause:
      ``` rust
      struct Test<T>
      where T: SomeTrait
      {
        ...
      }
      ```
- [x] Error messages
  - [x] Union
  - [x] Item with no generics
  - [x] No trait found
  - [x] Unit struct

All these tests have to account for:
- [ ] Copy
- [ ] Clone
- [ ] Debug
- [ ] Default
- [ ] Eq
- [ ] Hash
- [ ] Ord
- [ ] PartialEq
- [ ] PartialOrd
- [ ] Zeroize

**Comment by ModProg** [comment]
@daxpedda we should write down the things we want to test to make sure we can do that in an orderly fassion :D

**Comment by daxpedda** [comment]
I added some edge-cases to test.

**Comment by daxpedda** [comment]
I added a list of error messages to check, probably gonna expand on that.

**Comment by daxpedda** [comment]
So because we are currently using the built-in parser of syn, it's hard to make good custom error messages. In my opinion it's good enough like that, maybe we wanna improve this in the future, but it will require a complete revamp of our parsing.

**Comment by ModProg** [comment]
> So because we are currently using the built-in parser of syn, it's hard to make good custom error messages. In my opinion it's good enough like that, maybe we wanna improve this in the future, but it will require a complete revamp of our parsing.

I think they look good enough. But wouldn't we only need to map the error before returning it?

**Comment by daxpedda** [comment]
I tried that, but you can't know if the issue is parsing a type or duplicate comma. You can't introspect the error unless you start comparing the error message string.

On that note, I just had an idea (I think we talked about it before briefly): we could switch the syntax, let traits come first and then generic parameters.

Advantages:
- We could do some really good and precises error messages
- No weird forward parsing or anything else necessary
- Maybe easier because the difference between with or without generics is now left-to-right instead of right-to-left, considering we are typing in English and all

Disadvantages:
- No clue what's bad about this :sweat_smile:

**Comment by daxpedda** [comment]
More tests are still needed.
