### ISSUE TITLE
"skip" for enum variants with `PartialEq`

### ISSUE THREAD

**Issue by ModProg** [ModProg/derive-where#51]
The idea is to allow having incomparable variants always return false when compared.

Not sure what the best syntax is, but I'd say either `skip` or something like `uncompared`/`unequal`/`incomparable`

**Comment by ModProg** [comment]
I'm leaning towards incomparable, but not sure.

**Comment by daxpedda** [comment]
Isn't that already supported with `skip`?

**Comment by daxpedda** [comment]
Ah I see, right now if you use `skip` or `skip_inner` on variants or fields, it's just ignored during comparison but the comparison is then successful.
You are proposing that the comparison should fail instead.

Yeah definitely introducing a new word then `skip` would be appropriate here, `incomparable` sounds good to me?
