### ISSUE TITLE
`Debug` and skip could use `finish_non_exhaustive()`

### ISSUE THREAD

**Issue by daxpedda** [ModProg/derive-where#59]
I noticed when implementing some `Debug`s by hand that when I want to use skip I also use [`finish_non_exhaustive()`](https://doc.rust-lang.org/nightly/std/fmt/struct.DebugStruct.html#method.finish_non_exhaustive).

What do you think?

**Comment by ModProg** [comment]
makes perfect sense IMO

**Comment by ModProg** [comment]
One thing we need to decide is whether we can change this behavior in a minor version bump. I'd say yes, as the Debug formatting shouldn't be something depended on.

We could also just add a separate attribute for it, but I'd rather have it on by default and add a flag to disable than the other way round.

**Comment by daxpedda** [comment]
> One thing we need to decide is whether we can change this behavior in a minor version bump. I'd say yes, as the Debug formatting shouldn't be something depended on.

Agreed.

> We could also just add a separate attribute for it, but I'd rather have it on by default and add a flag to disable than the other way round.

I would add a flag to disable the new behavior, but I don't know how much more we should tag on to this library without actually knowing if anybody needs it.

**Comment by ModProg** [comment]
> I would add a flag to disable the new behavior, but I don't know how much more we should tag on to this library without actually knowing if anybody needs it.

Agreed.
