### ISSUE TITLE
Implement nightly implementation for `Ord`

### ISSUE THREAD

**Issue by daxpedda** [ModProg/derive-where#7]
This is related to #5.

On nightly a safe implementation can be done by using [`core::intrinsic::discriminant_value`](https://doc.rust-lang.org/core/intrinsics/fn.discriminant_value.html). This is unstable, but it can be avoided to use a feature in the top-level crate by using [`#[internal_unstable]`](https://doc.rust-lang.org/unstable-book/language-features/allow-internal-unstable.html).

This is also how `std` implements `PartialOrd` and `Ord`.

Obviously has to be hidden behind a crate feature.

**Comment by ModProg** [comment]
Does this need to be hidden behind a feature, or should we check for `nightly`?

**Comment by daxpedda** [comment]
Is it possible to check for nightly? The only thing I know of is this RFC: https://github.com/rust-lang/rust/issues/64796.

**Comment by ModProg** [comment]
you are correct, probably we should use a feature then, because this does not look very ideal:
https://stackoverflow.com/questions/49247618/check-whether-compiler-is-nightly-at-compile-time
