### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by daxpedda** [ModProg/derive-where#8]
Hook up CI:
- [ ] Dependabot
- [ ] cargo-audit
- [ ] Clippy
- [ ] rustfmt
- [ ] Build
  - [ ] `#[no_std]` build
  - [ ] MSRV build (#9) (https://crates.io/crates/cargo-msrv)
- [ ] Test
  - [ ] Unit and integration tests
  - [ ] Examples
  - [ ] `unsafe` feature (#5)
  - [ ] `nightly` feature (#7)

**Comment by ModProg** [comment]
use https://github.com/taiki-e/cargo-hack `--features-powerset --skip nightly` on stable and `--features-powerset` on nightly

**Comment by daxpedda** [comment]
Interesting, I would like to use it locally too, very useful!
