### ISSUE TITLE
Copy + Clone optimization is incorrect

### ISSUE THREAD

**Issue by akonradi-signal** [ModProg/derive-where#86]
The code [here](https://github.com/ModProg/derive-where/blob/d0dbebd33a27a7a8863445901004818e32f1088a/src/trait_/clone.rs#L52-L58) that special-cases deriving `Copy` and `Clone` bounds together is incorrect. Take, for example, the following type:

```rust
pub struct Wrapper<Inner, S> {
    inner: Inner,
    marker: PhantomData<S>,
}
```

A `#[derive_where(Copy, Clone; Inner)]` annotation will produce the following code:
```rust
impl<Inner, S> ::core::marker::Copy for Wrapper<Inner, S> where Inner: ::core::marker::Copy {}
impl<Inner, S> ::core::clone::Clone for Wrapper<Inner, S>
where
    Inner: ::core::clone::Clone,
{
    #[inline]
    fn clone(&self) -> Self {
        *self
    }
}
```

This [won't compile](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fa6a4dca39f47de6168770fa18727495) because the `Clone` impl can't prove that the type `Inner` implements `Copy` (correctly).

One solution is to require `Inner: Copy + Clone` in the annotation; that produces code that compiles, but that is overly restrictive since `Wrapper<Inner, S>` will only implement `Clone` if `Inner: Clone` _and_ `Inner: Copy`.

**Comment by daxpedda** [comment]
Already on it, but thank you!
