### ISSUE TITLE
Could 1.1 be re-published?

### ISSUE THREAD

**Issue by little-dude** [ModProg/derive-where#97]
Hello,

I'd like to use derive_where but I cannot use crates.io and am stuck with [Debian packages](https://packages.debian.org/stable/rust). I wanted to backport 1.1 since it depends on syn 1, which is packaged in Debian, but it has been yanked and I cannot force `debcargo`, the backporting tool, to package it.

Reading through the issue, it not super clear why this version was yanked. . Unless it suffers from a security vulnerability or bad correctness issue, would you consider re-publishing it crates.io ?

**Comment by little-dude** [comment]
Well I ended up packaging syn 2, so I'll be able to use the latest version of derive-where.

**Comment by daxpedda** [comment]
We didn't take enum representation into account when deriving `Partial/Ord`, which in some feature combination and in very specific cases could cause UB.

Which was fixed in v1.2.4 and we yanked all previous versions which contained this bug.

Glad you got your `syn` problem resolved though.
